export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const ASYNC_INCREMENT_ENTHUSIASM = "ASYNC_INCREMENT_ENTHUSIASM";
export type ASYNC_INCREMENT_ENTHUSIASM = typeof ASYNC_INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
