export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const ASYNC_INCREMENT_ENTHUSIASM = "ASYNC_INCREMENT_ENTHUSIASM";
export type ASYNC_INCREMENT_ENTHUSIASM = typeof ASYNC_INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const REQUEST_API_DATA = "REQUEST_API_DATA";
export type REQUEST_API_DATA = typeof REQUEST_API_DATA;

export const RECEIVE_API_DATA = "RECEIVE_API_DATA";
export type RECEIVE_API_DATA = typeof RECEIVE_API_DATA;

export const BASE_URI: string = "https://benweiser.com/wp-json/wp/v2/";
